name: Go

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Go-linter
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: ./...

    - name: Test
      run: go test -v ./...
